# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

run:
  timeout: 60m
  modules-download-mode: vendor

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - deadcode
    - durationcheck
    - errname
    - errcheck
    - exhaustive
    - exportloopref
    - gocritic
    - gofmt
    #- gofumpt
    - goimports
    - gosimple
    - govet
    - gosec
    #- godot
    - ineffassign
    - ifshort
    - nakedret
    - nilnil
    #- nolintlint
    - makezero
    - misspell
    - staticcheck
    - structcheck
    #- stylecheck
    - typecheck
    - unused
    - unconvert
    - unparam
    - varcheck
    - vet
    - vetshadow
    - whitespace
    #- wsl

linters-settings:
  errcheck:
    ignore: Set,fmt:.*,io:Close
  misspell:
    ignore-words:
      - hdinsight
      - exportfs
  nakedret:
    max-func-lines: 40
