issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - nakedret
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - unconvert
    - varcheck
    - vet
    - vetshadow

linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/helper/schema:ForceNew|Set,fmt:.*,io:Close

run:
  deadline: 10m10s
  modules-download-mode: vendor