---
name: Website Linting
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - 'website/**'
      - '.github/workflows/**'

jobs:
  website-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.23.0'
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make docs-lint
