---
name: Website Linting
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - 'website/**'
      - '.github/workflows/**'

jobs:
  website-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: '1.18.3'
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make docs-lint
