name: "Pull Request Triage"

on: [pull_request_target]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4.3.0
      with:
        configuration-path: .github/labeler-pull-request-triage.yml
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    # See also: https://github.com/CodelyTV/pr-size-labeler/pull/26
    - uses: CodelyTV/pr-size-labeler@c7a55a022747628b50f3eb5bf863b9e796b8f274 # v1.10.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        xs_label: 'size/XS'
        xs_max_size: '30'
        s_label: 'size/S'
        s_max_size: '60'
        m_label: 'size/M'
        m_max_size: '150'
        l_label: 'size/L'
        l_max_size: '300'
        xl_label: 'size/XL'
        message_if_xl: ''
